import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { BarChart3, Eye, Film, PlaySquare } from "lucide-react";
import { supabase } from "@/lib/site-client";
import { AdminHeading, MetricCard } from "@/components/app/AdminShell";

export const Route = createFileRoute("/_authenticated/kurucu/istatistikler")({ head: () => ({ meta: [{ title: "İstatistikler — Bilal Efendi" }, { name: "description", content: "İzlenme performansını ve öne çıkan içerikleri inceleyin." }, { property: "og:title", content: "İstatistikler — Bilal Efendi" }, { property: "og:description", content: "İzlenme performansını inceleyin." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Stats });
function Stats() {
  const query = useQuery({ queryKey: ["founder-stats"], queryFn: async () => { const since = new Date(Date.now() - 7 * 86400000).toISOString(); const [{ count: total }, { count: week }, { data: episodes }] = await Promise.all([supabase.from("episode_views").select("id", { count: "exact", head: true }), supabase.from("episode_views").select("id", { count: "exact", head: true }).gte("created_at", since), supabase.from("episodes").select("id,title,view_count,series(title)").order("view_count", { ascending: false }).limit(10)]); return { total: total ?? 0, week: week ?? 0, episodes: episodes ?? [] }; } });
  const data = query.data ?? { total: 0, week: 0, episodes: [] };
  const max = Math.max(1, ...data.episodes.map((e) => Number(e.view_count)));
  return <><AdminHeading title="İstatistikler" description="İçerik performansını ve izleyici ilgisini takip edin." /><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Toplam izlenme" value={data.total} icon={Eye} /><MetricCard label="Son 7 gün" value={data.week} icon={BarChart3} /><MetricCard label="İzlenen bölüm" value={data.episodes.filter((e) => Number(e.view_count) > 0).length} icon={PlaySquare} /></div><section className="mt-8"><h2 className="mb-4 flex items-center gap-2 text-lg font-semibold"><Film className="text-primary" /> En çok izlenen bölümler</h2><div className="space-y-3 rounded-lg border border-border bg-card p-4">{data.episodes.length === 0 && <p className="text-sm text-muted-foreground">İstatistik oluşturacak içerik yok.</p>}{data.episodes.map((e, i) => <div key={e.id} className="grid grid-cols-[24px_1fr_auto] items-center gap-3"><span className="text-sm font-bold text-muted-foreground">{i + 1}</span><div className="min-w-0"><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate">{e.title} <span className="text-muted-foreground">· {e.series?.title}</span></span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.max(2, Number(e.view_count) / max * 100)}%` }} /></div></div><span className="text-sm font-semibold">{e.view_count}</span></div>)}</div></section></>;
}