import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { ChevronDown, ChevronRight, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { AdminHeading } from "@/components/app/AdminShell";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type EpisodeForm = { id?: string; series_id: string; season_id: string; number: number; title: string; description: string; youtube_url: string; thumbnail_url: string; duration_seconds: number; status: "draft" | "published" | "hidden" | "scheduled" };
const blankEpisode: EpisodeForm = { series_id: "", season_id: "", number: 1, title: "", description: "", youtube_url: "", thumbnail_url: "", duration_seconds: 0, status: "draft" };
export const Route = createFileRoute("/_authenticated/kurucu/bolumler")({
  head: () => ({ meta: [{ title: "Sezon ve Bölümler — Bilal Efendi" }, { name: "description", content: "Sezonları ve YouTube bölümlerini yönetin." }, { property: "og:title", content: "Sezon ve Bölümler — Bilal Efendi" }, { property: "og:description", content: "Sezonları ve YouTube bölümlerini yönetin." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: EpisodesAdmin,
});
function EpisodesAdmin() {
  const qc = useQueryClient(); const [expanded, setExpanded] = useState<string[]>([]); const [episodeOpen, setEpisodeOpen] = useState(false); const [seasonOpen, setSeasonOpen] = useState(false); const [form, setForm] = useState<EpisodeForm>(blankEpisode); const [season, setSeason] = useState({ series_id: "", number: 1, title: "" });
  const series = useQuery({ queryKey: ["founder-content-tree"], queryFn: async () => { const { data, error } = await supabase.from("series").select("id,title,seasons(id,number,title,episodes(*))").order("title"); if (error) throw error; return data; } });
  const refresh = () => qc.invalidateQueries({ queryKey: ["founder-content-tree"] });
  async function saveSeason(e: React.FormEvent) { e.preventDefault(); const { error } = await supabase.from("seasons").insert({ series_id: season.series_id, number: season.number, title: season.title || null, sort_order: season.number }); if (error) toast.error(error.message); else { toast.success("Sezon eklendi"); setSeasonOpen(false); refresh(); } }
  async function saveEpisode(e: React.FormEvent) { e.preventDefault(); const payload = { series_id: form.series_id, season_id: form.season_id, number: form.number, title: form.title.trim(), description: form.description || null, youtube_url: form.youtube_url || null, thumbnail_url: form.thumbnail_url || null, duration_seconds: form.duration_seconds || null, status: form.status, sort_order: form.number }; const res = form.id ? await supabase.from("episodes").update(payload).eq("id", form.id) : await supabase.from("episodes").insert(payload); if (res.error) toast.error(res.error.message); else { toast.success("Bölüm kaydedildi"); setEpisodeOpen(false); refresh(); } }
  async function removeEpisode(id: string) { if (!confirm("Bölüm kalıcı olarak silinsin mi?")) return; await supabase.from("episodes").delete().eq("id", id); refresh(); }
  const seasons = series.data?.find((s) => s.id === form.series_id)?.seasons ?? [];
  return <><AdminHeading title="Sezon ve Bölümler" description="YouTube yayınlarını sezonlar altında düzenleyin." action={<div className="flex gap-2"><Button variant="secondary" onClick={() => setSeasonOpen(true)}><Plus /> Sezon</Button><Button onClick={() => { setForm(blankEpisode); setEpisodeOpen(true); }}><Plus /> Bölüm</Button></div>} />
    <div className="space-y-3">{series.data?.map((s) => { const isOpen = expanded.includes(s.id); const episodeCount = s.seasons.reduce((n, x) => n + x.episodes.length, 0); return <section key={s.id} className="rounded-lg border border-border bg-card"><button className="flex w-full items-center gap-3 p-4 text-left" onClick={() => setExpanded(isOpen ? expanded.filter((id) => id !== s.id) : [...expanded, s.id])}>{isOpen ? <ChevronDown /> : <ChevronRight />}<div className="flex-1"><h2 className="font-semibold">{s.title}</h2><p className="text-xs text-muted-foreground">{s.seasons.length} sezon · {episodeCount} bölüm</p></div></button>{isOpen && <div className="border-t border-border p-3">{s.seasons.length === 0 && <p className="p-3 text-sm text-muted-foreground">Bu seride henüz sezon yok.</p>}{[...s.seasons].sort((a,b) => a.number-b.number).map((sn) => <div key={sn.id} className="mb-4"><p className="mb-2 text-sm font-semibold text-primary">{sn.title || `${sn.number}. Sezon`}</p><div className="divide-y divide-border rounded-md border border-border">{sn.episodes.length === 0 && <p className="p-3 text-xs text-muted-foreground">Bölüm yok.</p>}{[...sn.episodes].sort((a,b) => a.number-b.number).map((e) => <div key={e.id} className="flex items-center gap-3 p-3"><span className="w-7 text-center text-xs text-muted-foreground">{e.number}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{e.title}</p><p className="text-xs text-muted-foreground">{e.status === "published" ? "Yayında" : "Taslak"} · {e.view_count} izlenme</p></div><Button variant="ghost" size="icon" onClick={() => { setForm({ id: e.id, series_id: e.series_id, season_id: e.season_id, number: e.number, title: e.title, description: e.description ?? "", youtube_url: e.youtube_url ?? "", thumbnail_url: e.thumbnail_url ?? "", duration_seconds: e.duration_seconds ?? 0, status: e.status }); setEpisodeOpen(true); }} aria-label="Düzenle"><Pencil /></Button><Button variant="ghost" size="icon" onClick={() => removeEpisode(e.id)} aria-label="Sil"><Trash2 className="text-destructive" /></Button></div>)}</div></div>)}</div>}</section>; })}</div>
    <Dialog open={seasonOpen} onOpenChange={setSeasonOpen}><DialogContent><DialogHeader><DialogTitle>Yeni sezon</DialogTitle></DialogHeader><form onSubmit={saveSeason} className="space-y-4"><Field label="Seri"><Select value={season.series_id} onValueChange={(v) => setSeason({ ...season, series_id: v })}><SelectTrigger><SelectValue placeholder="Seri seç" /></SelectTrigger><SelectContent>{series.data?.map((s) => <SelectItem key={s.id} value={s.id}>{s.title}</SelectItem>)}</SelectContent></Select></Field><Field label="Sezon numarası"><Input type="number" min={1} value={season.number} onChange={(e) => setSeason({ ...season, number: Number(e.target.value) })} /></Field><Field label="Sezon adı (isteğe bağlı)"><Input value={season.title} onChange={(e) => setSeason({ ...season, title: e.target.value })} /></Field><Button type="submit" className="w-full" disabled={!season.series_id}>Sezonu ekle</Button></form></DialogContent></Dialog>
    <Dialog open={episodeOpen} onOpenChange={setEpisodeOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{form.id ? "Bölümü düzenle" : "Yeni bölüm"}</DialogTitle></DialogHeader><form onSubmit={saveEpisode} className="grid gap-4 sm:grid-cols-2"><Field label="Seri"><Select value={form.series_id} onValueChange={(v) => setForm({ ...form, series_id: v, season_id: "" })}><SelectTrigger><SelectValue placeholder="Seri seç" /></SelectTrigger><SelectContent>{series.data?.map((s) => <SelectItem key={s.id} value={s.id}>{s.title}</SelectItem>)}</SelectContent></Select></Field><Field label="Sezon"><Select value={form.season_id} onValueChange={(v) => setForm({ ...form, season_id: v })}><SelectTrigger><SelectValue placeholder="Sezon seç" /></SelectTrigger><SelectContent>{seasons.map((s) => <SelectItem key={s.id} value={s.id}>{s.title || `${s.number}. Sezon`}</SelectItem>)}</SelectContent></Select></Field><Field label="Bölüm no"><Input type="number" min={0} value={form.number} onChange={(e) => setForm({ ...form, number: Number(e.target.value) })} /></Field><Field label="Yayın durumu"><Select value={form.status} onValueChange={(v: EpisodeForm["status"]) => setForm({ ...form, status: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">Taslak</SelectItem><SelectItem value="published">Yayında</SelectItem><SelectItem value="hidden">Gizli</SelectItem><SelectItem value="scheduled">Planlandı</SelectItem></SelectContent></Select></Field><Field label="Bölüm adı" className="sm:col-span-2"><Input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="YouTube adresi" className="sm:col-span-2"><Input required value={form.youtube_url} onChange={(e) => setForm({ ...form, youtube_url: e.target.value })} /></Field><Field label="Küçük görsel adresi"><Input value={form.thumbnail_url} onChange={(e) => setForm({ ...form, thumbnail_url: e.target.value })} /></Field><Field label="Süre (saniye)"><Input type="number" value={form.duration_seconds} onChange={(e) => setForm({ ...form, duration_seconds: Number(e.target.value) })} /></Field><Field label="Açıklama" className="sm:col-span-2"><Textarea rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><Button type="submit" className="sm:col-span-2" disabled={!form.series_id || !form.season_id}>Kaydet</Button></form></DialogContent></Dialog>
  </>;
}
function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <div className={className}><Label className="mb-1.5 block">{label}</Label>{children}</div>; }
