/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AraRouteImport } from './routes/ara'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as KategorilerRouteImport } from './routes/kategoriler'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as SerilerRouteImport } from './routes/seriler'
import { Route as AuthenticatedArkadaslarRouteImport } from './routes/_authenticated/arkadaslar'
import { Route as AuthenticatedKurucuRouteImport } from './routes/_authenticated/kurucu'
import { Route as AuthenticatedKurulumRouteImport } from './routes/_authenticated/kurulum'
import { Route as AuthenticatedMesajlarRouteImport } from './routes/_authenticated/mesajlar'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as IzleIdRouteImport } from './routes/izle.$id'
import { Route as SeriSlugRouteImport } from './routes/seri.$slug'
import { Route as AuthenticatedKurucuIndexRouteImport } from './routes/_authenticated/kurucu.index'
import { Route as AuthenticatedKurucuBolumlerRouteImport } from './routes/_authenticated/kurucu.bolumler'
import { Route as AuthenticatedKurucuIstatistiklerRouteImport } from './routes/_authenticated/kurucu.istatistikler'
import { Route as AuthenticatedKurucuKategorilerRouteImport } from './routes/_authenticated/kurucu.kategoriler'
import { Route as AuthenticatedKurucuKullanicilarRouteImport } from './routes/_authenticated/kurucu.kullanicilar'
import { Route as AuthenticatedKurucuSerilerRouteImport } from './routes/_authenticated/kurucu.seriler'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AraRoute = AraRouteImport.update({
  id: '/ara',
  path: '/ara',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorilerRoute = KategorilerRouteImport.update({
  id: '/kategoriler',
  path: '/kategoriler',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SerilerRoute = SerilerRouteImport.update({
  id: '/seriler',
  path: '/seriler',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArkadaslarRoute = AuthenticatedArkadaslarRouteImport.update({
  id: '/arkadaslar',
  path: '/arkadaslar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKurucuRoute = AuthenticatedKurucuRouteImport.update({
  id: '/kurucu',
  path: '/kurucu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKurulumRoute = AuthenticatedKurulumRouteImport.update({
  id: '/kurulum',
  path: '/kurulum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesajlarRoute = AuthenticatedMesajlarRouteImport.update({
  id: '/mesajlar',
  path: '/mesajlar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const IzleIdRoute = IzleIdRouteImport.update({
  id: '/izle/$id',
  path: '/izle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriSlugRoute = SeriSlugRouteImport.update({
  id: '/seri/$slug',
  path: '/seri/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKurucuIndexRoute =
  AuthenticatedKurucuIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKurucuRoute,
  } as any)
const AuthenticatedKurucuBolumlerRoute =
  AuthenticatedKurucuBolumlerRouteImport.update({
    id: '/bolumler',
    path: '/bolumler',
    getParentRoute: () => AuthenticatedKurucuRoute,
  } as any)
const AuthenticatedKurucuIstatistiklerRoute =
  AuthenticatedKurucuIstatistiklerRouteImport.update({
    id: '/istatistikler',
    path: '/istatistikler',
    getParentRoute: () => AuthenticatedKurucuRoute,
  } as any)
const AuthenticatedKurucuKategorilerRoute =
  AuthenticatedKurucuKategorilerRouteImport.update({
    id: '/kategoriler',
    path: '/kategoriler',
    getParentRoute: () => AuthenticatedKurucuRoute,
  } as any)
const AuthenticatedKurucuKullanicilarRoute =
  AuthenticatedKurucuKullanicilarRouteImport.update({
    id: '/kullanicilar',
    path: '/kullanicilar',
    getParentRoute: () => AuthenticatedKurucuRoute,
  } as any)
const AuthenticatedKurucuSerilerRoute =
  AuthenticatedKurucuSerilerRouteImport.update({
    id: '/seriler',
    path: '/seriler',
    getParentRoute: () => AuthenticatedKurucuRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ara': typeof AraRoute
  '/giris': typeof GirisRoute
  '/kategoriler': typeof KategorilerRoute
  '/premium': typeof PremiumRoute
  '/seriler': typeof SerilerRoute
  '/arkadaslar': typeof AuthenticatedArkadaslarRoute
  '/kurucu': typeof AuthenticatedKurucuRouteWithChildren
  '/kurulum': typeof AuthenticatedKurulumRoute
  '/mesajlar': typeof AuthenticatedMesajlarRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/izle/$id': typeof IzleIdRoute
  '/seri/$slug': typeof SeriSlugRoute
  '/kurucu/bolumler': typeof AuthenticatedKurucuBolumlerRoute
  '/kurucu/istatistikler': typeof AuthenticatedKurucuIstatistiklerRoute
  '/kurucu/kategoriler': typeof AuthenticatedKurucuKategorilerRoute
  '/kurucu/kullanicilar': typeof AuthenticatedKurucuKullanicilarRoute
  '/kurucu/seriler': typeof AuthenticatedKurucuSerilerRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/kurucu/': typeof AuthenticatedKurucuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ara': typeof AraRoute
  '/giris': typeof GirisRoute
  '/kategoriler': typeof KategorilerRoute
  '/premium': typeof PremiumRoute
  '/seriler': typeof SerilerRoute
  '/arkadaslar': typeof AuthenticatedArkadaslarRoute
  '/kurulum': typeof AuthenticatedKurulumRoute
  '/mesajlar': typeof AuthenticatedMesajlarRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/izle/$id': typeof IzleIdRoute
  '/seri/$slug': typeof SeriSlugRoute
  '/kurucu/bolumler': typeof AuthenticatedKurucuBolumlerRoute
  '/kurucu/istatistikler': typeof AuthenticatedKurucuIstatistiklerRoute
  '/kurucu/kategoriler': typeof AuthenticatedKurucuKategorilerRoute
  '/kurucu/kullanicilar': typeof AuthenticatedKurucuKullanicilarRoute
  '/kurucu/seriler': typeof AuthenticatedKurucuSerilerRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/kurucu': typeof AuthenticatedKurucuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ara': typeof AraRoute
  '/giris': typeof GirisRoute
  '/kategoriler': typeof KategorilerRoute
  '/premium': typeof PremiumRoute
  '/seriler': typeof SerilerRoute
  '/_authenticated/arkadaslar': typeof AuthenticatedArkadaslarRoute
  '/_authenticated/kurucu': typeof AuthenticatedKurucuRouteWithChildren
  '/_authenticated/kurulum': typeof AuthenticatedKurulumRoute
  '/_authenticated/mesajlar': typeof AuthenticatedMesajlarRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/izle/$id': typeof IzleIdRoute
  '/seri/$slug': typeof SeriSlugRoute
  '/_authenticated/kurucu/bolumler': typeof AuthenticatedKurucuBolumlerRoute
  '/_authenticated/kurucu/istatistikler': typeof AuthenticatedKurucuIstatistiklerRoute
  '/_authenticated/kurucu/kategoriler': typeof AuthenticatedKurucuKategorilerRoute
  '/_authenticated/kurucu/kullanicilar': typeof AuthenticatedKurucuKullanicilarRoute
  '/_authenticated/kurucu/seriler': typeof AuthenticatedKurucuSerilerRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/kurucu/': typeof AuthenticatedKurucuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ara'
    | '/giris'
    | '/kategoriler'
    | '/premium'
    | '/seriler'
    | '/arkadaslar'
    | '/kurucu'
    | '/kurulum'
    | '/mesajlar'
    | '/profil'
    | '/izle/$id'
    | '/seri/$slug'
    | '/kurucu/bolumler'
    | '/kurucu/istatistikler'
    | '/kurucu/kategoriler'
    | '/kurucu/kullanicilar'
    | '/kurucu/seriler'
    | '/u/$username'
    | '/kurucu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ara'
    | '/giris'
    | '/kategoriler'
    | '/premium'
    | '/seriler'
    | '/arkadaslar'
    | '/kurulum'
    | '/mesajlar'
    | '/profil'
    | '/izle/$id'
    | '/seri/$slug'
    | '/kurucu/bolumler'
    | '/kurucu/istatistikler'
    | '/kurucu/kategoriler'
    | '/kurucu/kullanicilar'
    | '/kurucu/seriler'
    | '/u/$username'
    | '/kurucu'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ara'
    | '/giris'
    | '/kategoriler'
    | '/premium'
    | '/seriler'
    | '/_authenticated/arkadaslar'
    | '/_authenticated/kurucu'
    | '/_authenticated/kurulum'
    | '/_authenticated/mesajlar'
    | '/_authenticated/profil'
    | '/izle/$id'
    | '/seri/$slug'
    | '/_authenticated/kurucu/bolumler'
    | '/_authenticated/kurucu/istatistikler'
    | '/_authenticated/kurucu/kategoriler'
    | '/_authenticated/kurucu/kullanicilar'
    | '/_authenticated/kurucu/seriler'
    | '/_authenticated/u/$username'
    | '/_authenticated/kurucu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AraRoute: typeof AraRoute
  GirisRoute: typeof GirisRoute
  KategorilerRoute: typeof KategorilerRoute
  PremiumRoute: typeof PremiumRoute
  SerilerRoute: typeof SerilerRoute
  IzleIdRoute: typeof IzleIdRoute
  SeriSlugRoute: typeof SeriSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ara': {
      id: '/ara'
      path: '/ara'
      fullPath: '/ara'
      preLoaderRoute: typeof AraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategoriler': {
      id: '/kategoriler'
      path: '/kategoriler'
      fullPath: '/kategoriler'
      preLoaderRoute: typeof KategorilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seriler': {
      id: '/seriler'
      path: '/seriler'
      fullPath: '/seriler'
      preLoaderRoute: typeof SerilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/arkadaslar': {
      id: '/_authenticated/arkadaslar'
      path: '/arkadaslar'
      fullPath: '/arkadaslar'
      preLoaderRoute: typeof AuthenticatedArkadaslarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kurucu': {
      id: '/_authenticated/kurucu'
      path: '/kurucu'
      fullPath: '/kurucu'
      preLoaderRoute: typeof AuthenticatedKurucuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kurulum': {
      id: '/_authenticated/kurulum'
      path: '/kurulum'
      fullPath: '/kurulum'
      preLoaderRoute: typeof AuthenticatedKurulumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesajlar': {
      id: '/_authenticated/mesajlar'
      path: '/mesajlar'
      fullPath: '/mesajlar'
      preLoaderRoute: typeof AuthenticatedMesajlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/izle/$id': {
      id: '/izle/$id'
      path: '/izle/$id'
      fullPath: '/izle/$id'
      preLoaderRoute: typeof IzleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seri/$slug': {
      id: '/seri/$slug'
      path: '/seri/$slug'
      fullPath: '/seri/$slug'
      preLoaderRoute: typeof SeriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kurucu/': {
      id: '/_authenticated/kurucu/'
      path: '/'
      fullPath: '/kurucu/'
      preLoaderRoute: typeof AuthenticatedKurucuIndexRouteImport
      parentRoute: typeof AuthenticatedKurucuRoute
    }
    '/_authenticated/kurucu/bolumler': {
      id: '/_authenticated/kurucu/bolumler'
      path: '/bolumler'
      fullPath: '/kurucu/bolumler'
      preLoaderRoute: typeof AuthenticatedKurucuBolumlerRouteImport
      parentRoute: typeof AuthenticatedKurucuRoute
    }
    '/_authenticated/kurucu/istatistikler': {
      id: '/_authenticated/kurucu/istatistikler'
      path: '/istatistikler'
      fullPath: '/kurucu/istatistikler'
      preLoaderRoute: typeof AuthenticatedKurucuIstatistiklerRouteImport
      parentRoute: typeof AuthenticatedKurucuRoute
    }
    '/_authenticated/kurucu/kategoriler': {
      id: '/_authenticated/kurucu/kategoriler'
      path: '/kategoriler'
      fullPath: '/kurucu/kategoriler'
      preLoaderRoute: typeof AuthenticatedKurucuKategorilerRouteImport
      parentRoute: typeof AuthenticatedKurucuRoute
    }
    '/_authenticated/kurucu/kullanicilar': {
      id: '/_authenticated/kurucu/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/kurucu/kullanicilar'
      preLoaderRoute: typeof AuthenticatedKurucuKullanicilarRouteImport
      parentRoute: typeof AuthenticatedKurucuRoute
    }
    '/_authenticated/kurucu/seriler': {
      id: '/_authenticated/kurucu/seriler'
      path: '/seriler'
      fullPath: '/kurucu/seriler'
      preLoaderRoute: typeof AuthenticatedKurucuSerilerRouteImport
      parentRoute: typeof AuthenticatedKurucuRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedKurucuRouteChildren {
  AuthenticatedKurucuBolumlerRoute: typeof AuthenticatedKurucuBolumlerRoute
  AuthenticatedKurucuIstatistiklerRoute: typeof AuthenticatedKurucuIstatistiklerRoute
  AuthenticatedKurucuKategorilerRoute: typeof AuthenticatedKurucuKategorilerRoute
  AuthenticatedKurucuKullanicilarRoute: typeof AuthenticatedKurucuKullanicilarRoute
  AuthenticatedKurucuSerilerRoute: typeof AuthenticatedKurucuSerilerRoute
  AuthenticatedKurucuIndexRoute: typeof AuthenticatedKurucuIndexRoute
}

const AuthenticatedKurucuRouteChildren: AuthenticatedKurucuRouteChildren = {
  AuthenticatedKurucuBolumlerRoute: AuthenticatedKurucuBolumlerRoute,
  AuthenticatedKurucuIstatistiklerRoute: AuthenticatedKurucuIstatistiklerRoute,
  AuthenticatedKurucuKategorilerRoute: AuthenticatedKurucuKategorilerRoute,
  AuthenticatedKurucuKullanicilarRoute: AuthenticatedKurucuKullanicilarRoute,
  AuthenticatedKurucuSerilerRoute: AuthenticatedKurucuSerilerRoute,
  AuthenticatedKurucuIndexRoute: AuthenticatedKurucuIndexRoute,
}

const AuthenticatedKurucuRouteWithChildren =
  AuthenticatedKurucuRoute._addFileChildren(AuthenticatedKurucuRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArkadaslarRoute: typeof AuthenticatedArkadaslarRoute
  AuthenticatedKurucuRoute: typeof AuthenticatedKurucuRouteWithChildren
  AuthenticatedKurulumRoute: typeof AuthenticatedKurulumRoute
  AuthenticatedMesajlarRoute: typeof AuthenticatedMesajlarRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArkadaslarRoute: AuthenticatedArkadaslarRoute,
  AuthenticatedKurucuRoute: AuthenticatedKurucuRouteWithChildren,
  AuthenticatedKurulumRoute: AuthenticatedKurulumRoute,
  AuthenticatedMesajlarRoute: AuthenticatedMesajlarRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AraRoute: AraRoute,
  GirisRoute: GirisRoute,
  KategorilerRoute: KategorilerRoute,
  PremiumRoute: PremiumRoute,
  SerilerRoute: SerilerRoute,
  IzleIdRoute: IzleIdRoute,
  SeriSlugRoute: SeriSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
